poem_backend/poem_app/urls.py
# encoding: utf-8

'''
@author: sunyue
@contact: sunyue@mail.ynu.edu.cn
@software: pycharm
@file: urls.py
@time: 2019/6/16
@desc: 
'''

from django.urls import path
from poem_app import views

app_name = 'poem_app'
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('index/',views.index,name='登陆'),
    path('register/',views.regist,name='注册'),
    path('log/', views.log, name='历史纪录' ),
    path('main/',views.main),
    path('get_valid_img.png/', views.get_valid_img),
    path('sendMsg/', views.sendMsg, name='sendMsg', ),
    path('get_rand_poem/', views.get_rand_poem, name='get_rand_poem', ),
    path('f_poem/', views.f_poem, name='f_poem', ),
    path('s_poem/', views.s_poem, name='s_poem', ),
    path('get_rand_sing/', views.get_rand_poem, name='get_rand_poem', ),

]

poem_backend/poem_backend/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('poem_app/', include('poem_app.urls')),
    path('admin/', admin.site.urls),
    # path('captcha/', include('captcha.urls')),
]


# from django.urls import path
# from poem_app import views
# app_name = 'poem_app'
# urlpatterns = [
#     # path('admin/', admin.site.urls),
#     path('index/',views.index,name='登陆'),
#     path('register/',views.regist,name='注册'),
#     path('main/',views.main),
#     path('get_valid_img.png/', views.get_valid_img),
#     # url(r'^send_message$', views.send_message, name='send_message'),
#     path('sendMsg/', views.sendMsg, name='sendMsg', ),
#     # path('s/', views.s, name='s', )
# ]

poem_backend/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <title>登录</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'css/common.css' %}" />
{#    <link rel="stylesheet" href="css/reset.css" />#}
{#    <link rel="stylesheet" href="css/common.css" />#}

{#    <link href="{%static 'css/drag.css'%}" rel="stylesheet" type="text/css">#}
{#    <script src="{% js/jquery.min.js %}" type="text/javascript"></script>#}
{#    <script src="{% static 'js/drag.js' %}" type="text/javascript"></script>#}
</head>
<body>
    <div class="wrap login_wrap" style="background-image: url({% static 'img/bg6.jpg'%})">
        <div class="content">

            <!--<div class="logo"></div>-->

            <div class="login_box">

                <div class="login_form">
                    <div class="login_title">
                        登录
                    </div>
                    <form action="" method="post">
                        {%  csrf_token %}
                        <div class="form_check_ipt">
                            <div style="text-align: center;color: red;font-size: 15px;">{{ error }}</div>
                        </div>


                        <div class="form_text_ipt">
                            <input name="username" type="text" placeholder="账号">
                        </div>
                        <div class="ececk_warning"><span>数据不能为空</span></div>

                        <div class="form_text_ipt">
                            <input name="password" type="password" placeholder="密码">
                        </div>
                        <div class="ececk_warning"><span>数据不能为空</span></div>

                        <div style="width: 300px;height: 40px;border:0" class="form_check_ipt"  >
{#                            <label for="password" class="col-sm-2 control-label">验证码</label>#}
                            <div class="" style="border: solid 1px #CCCCCC;height: 38px;width: 130px;float: left">
                                <input style="line-height: 35px;width: 120px;border: 0" type="text" name="valid_code" id="valid_code" placeholder="请输入验证码">
                            </div>
                            <div style="float: right;width:160px ;height: 40px;line-height: 40px">
                                <img onclick="refresh(this)" style="" id="valid-img" class="valid-img" src="/poem_app/get_valid_img.png?" alt="">
                            </div>
                        </div>

                        <!--<div class="slid">-->
                            <!--<center><br><br><br><div id="drag"></div></center>-->
                            <!--<script type="text/javascript">-->
                                <!--$('#drag').drag();-->
                            <!--</script>-->
                        <!--</div>-->
                        <!--<br>-->

{#                        <div class="ececk_warning"><span>数据不能为空</span></div>#}
{##}
{#                        <div class="form_check_ipt">#}
{#                            <div class="left check_left">#}
{#                                <label><input name="" type="checkbox"> 下次自动登录</label>#}
{#                            </div>#}
{#                            <div class="right check_right">#}
{#                                <a href="#">忘记密码</a>#}
{#                            </div>#}
{#                        </div>#}

                        <div class="form_btn">
                            <button type="submit" >登录</button>
                            <!--<input type="submit" name="sub" onclick="return juge()" value="登陆">-->
                        </div>


                        <div class="form_reg_btn">
                            <span>还没有帐号？</span><a href="/poem_app/register/">马上注册</a>
                        </div>
                    </form>
{#                    <div class="other_login">#}
{#                        <div class="left other_left">#}
{#                            <span>其它登录方式</span>#}
{#                        </div>#}
{#                        <div class="right other_right">#}
{#                            <a href="#">QQ登录</a>#}
{#                            <a href="#">微信登录</a>#}
{#                        </div>#}
{#                    </div>#}
                    <br>
                        <br>
                        <br>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
    // 点击验证码图片 刷新验证码
    $("#valid-img").click(function () {
        $(this)[0].src += "?";
    })
    function refresh(obj) {
    obj.src += Math.random()//(new Date()).gettime()
}
    </script>
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/common.js' %}" ></script>
</body>
</html>

poem_backend/templates/log.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>log</title>
    <link rel="stylesheet" href="{% static 'css/log.css' %}" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}" ></script>
    <!--<link rel="stylesheet" href="css/main.css" />-->
</head>
<body>
<header>
    <div class="menu">
        <a href="/poem_app/main/">返回</a>
    </div>
</header>


<!--顶部图-->
<div class="bg" >
    <div class="poem_div" style="padding-left: 30px;padding-top: 30px;">
        {% for item in data%}
            {% for info in item%}
        <p style="color:#fff; ">{{ info }}</p>
                {% endfor %}
        {% endfor %}
    </div>
</div>
<!--</div>-->

</body>
</html>

poem_backend/templates/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<meta charset="utf-8">
		<title>注册</title>
		<link rel="stylesheet" href="{% static 'css/reset.css' %}" />
        <link rel="stylesheet" href="{% static 'css/common.css' %}" />
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}" ></script>
	</head>
	<body>
		<div class="wrap login_wrap"  style="background-image: url({% static 'img/bg6.jpg'%})">
			<div class="content">
				<!--<div class="logo"></div>-->
				<div class="login_box">

					<div class="login_form">
						<div class="login_title">
							注册
						</div>
						<form action="" method="post">
                            {%  csrf_token %}
                            <div class="form_check_ipt">
                                <div style="text-align: center;color: red;font-size: 15px;">{{ error }}</div>
                            </div>

                            <div style="width: 300px;height: 40px;border:0" class="form_check_ipt"  >
                                <div class="" style="line-height: 40px;border: solid 1px #CCCCCC;height: 38px;width: 170px;float: left">
                                    <input style="line-height: 35px;width: 160px;border: 0" type="text" name="valid_code" id="valid_code" placeholder="请输入手机号">
                                </div>

                                <div style="float: right;width:125px ;height: 40px;line-height: 40px">
                                    <input    style="background: white; width: 125px ;float: left ;line-height: 40px;height: 40px;" type="button" id="btnSendCode" value="发送验证码" onclick="sendMessage()" >
                                </div>
                            </div>

                            <div class="form_text_ipt">
								<input id="yzcode" name="yzcode" type="text" placeholder="请输入验证码">
    						</div>

							<div class="ececk_warning"><span>数据不能为空</span></div>

{#                            <div class="form_text_ipt">#}
{#								<input name="username" type="text" placeholder="用户名">#}
{#							</div>#}
{#							<div class="ececk_warning"><span>数据不能为空</span></div>#}

							<div class="form_text_ipt">
								<input name="password" type="password" placeholder="密码">
							</div>
							<div class="ececk_warning"><span>数据不能为空</span></div>
							<div class="form_text_ipt">
								<input name="repassword" type="password" placeholder="重复密码">
							</div>
							<div class="ececk_warning"><span>数据不能为空</span></div>



							<div class="form_btn">
								<button type="submit">注册</button>
							</div>
							<div class="form_reg_btn">
								<span>已有帐号？</span><a href="/poem_app/index/">马上登录</a>
							</div>
						</form>
{#						<div class="other_login">#}
{#							<div class="left other_left">#}
{#								<span>其它登录方式</span>#}
{#							</div>#}
{#							<div class="right other_right">#}
{#								<a href="#">QQ登录</a>#}
{#								<a href="#">微信登录</a>#}
{#								<a href="#">微博登录</a>#}
{#							</div>#}
{#						</div>#}
                        <br>
                        <br>
                        <br>
					</div>
				</div>
			</div>
		</div>
        <script type="text/javascript">

            var InterValObj; //timer变量，控制时间
            var count = 60; //间隔函数，1秒执行
            var curCount;//当前剩余秒数
            function sendMessage() {
                curCount = count;
                //设置button效果，开始计时
                $("#btnSendCode").attr("disabled", "true");
                $("#btnSendCode").val(curCount + "秒");
                InterValObj = window.setInterval(SetRemainTime, 1000); //启动计时器，1秒执行一次
                //请求后台发送验证码
            }
            //timer处理函数
            function SetRemainTime() {
                if (curCount == 0) {
                    window.clearInterval(InterValObj);//停止计时器
                    $("#btnSendCode").removeAttr("disabled");//启用按钮
                    $("#btnSendCode").val("重新发送验证码");
                }
                else {
                    curCount--;
                    $("#btnSendCode").val(curCount + "秒");
                }
            }
		</script>

        <!--向后台通过ajax发送手机号码数据-->
        <script>
            $('#btnSendCode').click(function () {
                $.ajax({
                    {#cache:false,#}
                    type:"GET",
                    url:"{% url 'poem_app:sendMsg' %}",
                    data:{
                       {#csrfmiddlewaretoken:$('[name="csrfmiddlewaretoken"]').val(),#}
                       mobile:$("#valid_code").val()
                    },
                    async:true,
                    success:function (data) {
                        alert(data)
                    }
                })
            })

        </script>

		<script type="text/javascript" src="{% static 'js/jquery.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/common.js' %}" ></script>

	</body>
</html>